---
application:
  name: "qovery-wordpress"
  project: "TestProject"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "flints"
  version: "5.6"
routers:
- name: "main-qovery-wordpress"
  routes:
  - application_name: "qovery-wordpress"
    paths:
    - "/*"
