---
application:
  name: "qovery-wordpress"
  project: "ProjectTest"
  organization: "QoveryCommunity"
  storage:
  - name: "stones"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/stones"
databases:
- type: "MYSQL"
  name: "flints"
  version: "8.0"
routers:
- name: "main-qovery-wordpress"
  routes:
  - application_name: "qovery-wordpress"
    paths:
    - "/*"
