---
application:
  name: "qovery-wordpress"
  project: "Garbageman"
  organization: "QoveryCommunity"
  storage:
  - name: "Poop"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/Poop"
databases:
- type: "MYSQL"
  name: "Flints"
  version: "5.6"
routers:
- name: "main-qovery-wordpress"
  routes:
  - application_name: "qovery-wordpress"
    paths:
    - "/*"
